fix(repo-doctor): Moment and Material-UI should not be dependencies
cozy/cozy-libs pull request #1530
Opened 2022-04-12 12:37 UTC by trollepierre

According to our [guidelines](https://github.com/cozy/cozy-guidelines), material-ui and moment should not be set as dependencies.
This decision has been taken during Front meeting of 12th April

<img width="768" alt="Capture d’écran 2022-04-12 à 14 34 48" src="https://user-images.githubusercontent.com/8363334/162963614-866e76eb-9069-40c0-b1d0-7c6f31fa842e.png">

2022-04-13 06:53 UTC, Crash-- requested changes
I don't understand. Material-ui is declarated as a peerDep of cozy-ui. So the app needs to have material-ui as dep... 

This is inside our libs that material-ui should not be added as dep

2022-04-13 12:16 UTC, trollepierre commented
@Crash-- : 
let's fix this LGTM issue : https://github.com/cozy/cozy-ui/issues/1865
if you approve that https://github.com/cozy/cozy-ui/pull/2094
that would unblock your requested change.

2022-04-14 15:16 UTC, acezard approved these changes

2023-02-08 07:51 UTC, Crash-- approved these changes

2023-02-08 08:46 UTC, merged