fix(harvest): Enhance USER_ACTION_NEEDED messages
cozy/cozy-libs pull request #2368
Opened 2023-12-21 16:08 UTC by LucsT

Enhance error message about Terms of service.

Maybe this PR need a rework of default USER_ACTION_NEEDED message too.

2023-12-21 16:12 UTC, doubleface commented on packages/cozy-harvest-lib/src/locales/fr.json
> +        "title": "Des nouvelles conditions d'utilisation sont à valider",
C'est pas conditions générales d'utilisation, le terme consacré justement ?

2023-12-29 12:40 UTC, Crash-- commented on packages/cozy-harvest-lib/src/locales/fr.json
> +        "title": "Des nouvelles conditions d'utilisation sont à valider",
@LucsT 🙏

2024-01-08 08:44 UTC, doubleface approved these changes

2024-01-08 08:46 UTC, Crash-- commented on packages/cozy-harvest-lib/src/locales/fr.json
> +        "title": "Des nouvelles générales conditions d'utilisation sont à valider",
> Des nouvelles générales conditions d'utilisation sont à valider

c'est pas très français. 

> Des nouvelles conditions générales d'utilisation sont à valider

C'est mieux ?

2024-01-08 08:46 UTC, Crash-- requested changes
see comment

2024-01-08 09:11 UTC, Crash-- approved these changes

2024-01-08 09:26 UTC, merged